// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeFlow.Modules.Catalog.Infrastructure.Persistence;

#nullable disable

namespace TradeFlow.Modules.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260730113938_AddCatalogTaxCategories")]
    partial class AddCatalogTaxCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradeFlow.Modules.Catalog.Domain.ProductCategories.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductCategories_OrganisationId_Code");

                    b.HasIndex("OrganisationId", "Status")
                        .HasDatabaseName("IX_ProductCategories_OrganisationId_Status");

                    b.ToTable("ProductCategories", "catalog");
                });

            modelBuilder.Entity("TradeFlow.Modules.Catalog.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SKU");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("TaxCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId")
                        .HasDatabaseName("IX_Products_ProductCategoryId");

                    b.HasIndex("TaxCategoryId")
                        .HasDatabaseName("IX_Products_TaxCategoryId");

                    b.HasIndex("UnitOfMeasureId")
                        .HasDatabaseName("IX_Products_UnitOfMeasureId");

                    b.HasIndex("OrganisationId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_OrganisationId_Sku");

                    b.HasIndex("OrganisationId", "Status")
                        .HasDatabaseName("IX_Products_OrganisationId_Status");

                    b.ToTable("Products", "catalog");
                });

            modelBuilder.Entity("TradeFlow.Modules.Catalog.Domain.TaxCategories.TaxCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_TaxCategories_Code");

                    b.HasIndex("Status", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("IX_TaxCategories_Status_EffectiveFrom_EffectiveTo");

                    b.ToTable("TaxCategories", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_TaxCategories_EffectivePeriod", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");

                            t.HasCheckConstraint("CK_TaxCategories_Rate", "[Rate] >= 0 AND [Rate] <= 1");

                            t.HasCheckConstraint("CK_TaxCategories_TreatmentRate", "([Treatment] = 'StandardRated' AND [Rate] > 0) OR ([Treatment] IN ('ZeroRated', 'Exempt') AND [Rate] = 0)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "GST15",
                            Description = "Standard-rated supplies at 15% GST.",
                            EffectiveFrom = new DateOnly(2010, 10, 1),
                            Name = "Standard GST",
                            Rate = 0.1500m,
                            Status = "Active",
                            Treatment = "StandardRated"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "GST0",
                            Description = "Zero-rated supplies charged at 0% GST.",
                            EffectiveFrom = new DateOnly(2010, 10, 1),
                            Name = "Zero-rated GST",
                            Rate = 0m,
                            Status = "Active",
                            Treatment = "ZeroRated"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "EXEMPT",
                            Description = "Supplies that are exempt from GST.",
                            EffectiveFrom = new DateOnly(2010, 10, 1),
                            Name = "GST exempt",
                            Rate = 0m,
                            Status = "Active",
                            Treatment = "Exempt"
                        });
                });

            modelBuilder.Entity("TradeFlow.Modules.Catalog.Domain.UnitsOfMeasure.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_UnitsOfMeasure_Code");

                    b.ToTable("UnitsOfMeasure", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_UnitsOfMeasure_Code", "[Code] IN ('EA', 'KG', 'L', 'M')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "EA",
                            Name = "Each",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "KG",
                            Name = "Kilogram",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "L",
                            Name = "Litre",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "M",
                            Name = "Metre",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("TradeFlow.Modules.Catalog.Domain.Products.Product", b =>
                {
                    b.HasOne("TradeFlow.Modules.Catalog.Domain.ProductCategories.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Products_ProductCategories_ProductCategoryId");

                    b.HasOne("TradeFlow.Modules.Catalog.Domain.TaxCategories.TaxCategory", null)
                        .WithMany()
                        .HasForeignKey("TaxCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Products_TaxCategories_TaxCategoryId");

                    b.HasOne("TradeFlow.Modules.Catalog.Domain.UnitsOfMeasure.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Products_UnitsOfMeasure_UnitOfMeasureId");
                });
#pragma warning restore 612, 618
        }
    }
}
